version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
