export const TASK = {
  CREATE_TASK_TITLE: "Create a Task",
  TITLE_LABEL: "Title",
  DESCRIPTION_LABEL: "Description",
  ASSIGN_TO_LABEL: "Assign To",
  ASSIGN_TO_ME_BUTTON: "Assign to Me",
  SEARCH_USER_PLACEHOLDER: "Search user...",
  CREATE_BUTTON: "Create Task",
  SELECT_TASK_VIEW_PLACEHOLDER: "Select Task View",
  TASK_CREATED_TOAST_TITLE: "Task Created",
  TASK_CREATED_TOAST_DESC: "Your task has been successfully created.",
  TASK_UPDATED_TOAST_TITLE: "Task Updated",
  TASK_UPDATED_TOAST_DESC: "Your task has been successfully updated.",
  TASK_UPDATE_FAILED_TITLE: "Update Failed",
  TASK_UPDATE_FAILED_DESC: "Could not update task.",
  CREATED_TASKS_LABEL: "My Created Tasks",
  ASSIGNED_TASKS_LABEL: "Tasks Assigned to Me",
  TITLE_REQUIRED: "Title is required.",
  ASSIGNEDTO_REQUIRED: "Please select a valid user from suggestions.",
  STATUS_OPTIONS: [
    { label: "To Do", value: "TODO" },
    { label: "In Progress", value: "IN_PROGRESS" },
    { label: "Done", value: "DONE" },
  ],
  TASK_VIEW_OPTIONS: [
    { label: "Created Tasks", value: "created" },
    { label: "Assigned Tasks", value: "assigned" },
  ],
  STATUS: ["TODO", "IN_PROGRESS", "DONE"],
  EDIT_TASK_TITLE: "Edit Task",
  PLACEHOLDER_DESCRIPTION: "Enter details or comments...",
  PLACEHOLDER_STATUS: "Status",
  ASSIGNED_TO_LABEL: "Assigned To",
  ASSIGNED_BY_LABEL: "Assigned By",
  STATUS_LABEL: "Status",

  NO_TASKS_TEXT: "No tasks",
  UNKNOWN_USER: "Unknown",
};
