openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API documentation for the Task Management App
servers:
  - url: http://localhost:3001
paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, firstName, lastName]
              properties:
                email:
                  type: string
                password:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        200:
          description: User registered successfully
        400:
          description: Bad Request
  /api/auth/login:
    post:
      summary: Login a user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
        401:
          description: Invalid credentials
  /api/tasks:
    post:
      summary: Create a new task
      tags: [Tasks]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title]
              properties:
                title:
                  type: string
                description:
                  type: string
                assignedToId:
                  type: string
      responses:
        201:
          description: Task created
        400:
          description: Invalid input
    get:
      summary: Get all tasks
      tags: [Tasks]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of tasks
        401:
          description: Unauthorized
  /api/tasks/{id}:
    put:
      summary: Update a task
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
      responses:
        200:
          description: Task updated
        400:
          description: Invalid input
        404:
          description: Task not found
    delete:
      summary: Delete a task
      tags: [Tasks]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          description: Task deleted
        404:
          description: Task not found
  /api/users:
    get:
      summary: Get all users
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
  /api/users/search:
    get:
      summary: Search users
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search query string
      responses:
        200:
          description: List of users matching the search
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        401:
          description: Unauthorized
        500:
          description: Internal Server Error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
